# Generated by Django 3.2.8 on 2021-11-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Code', models.CharField(max_length=25)),
                ('Duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Mobile', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Father_Name', models.CharField(max_length=25)),
                ('Roll_No', models.IntegerField()),
                ('School_Name', models.CharField(max_length=30)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.instructor'),
        ),
    ]
